
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- ./deployment/
- ./deployment2/

labels:
- includeSelectors: true
  pairs:
    app: test-app
    env: dev

patches:
- path: patches/replicas-0.yaml
  target:
    labelSelector: app=test-app
