apiVersion: apps/v1
kind: Deployment
metadata:
  name: other-thing
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    spec:
      containers:
        -
          name: main
          image: application
          imagePullPolicy: IfNotPresent
